### ISSUE TITLE
Gifski doesn't finish enabling

### ISSUE THREAD

**Issue by MattieTK** [sindresorhus/kap-gifski#2]
_Imported from https://github.com/wulkano/kap/issues/768_

**macOS version:** 10.15.1
**Kap version:** 3.0.0

#### Steps to reproduce
Try to toggle on gifski

#### Current behaviour
Gifski attempts to install (hangs in the toggled on state)
Gifski fails to enable (falls back to off state)

![Screen Recording 2019-11-28 at 16 45 32 2019-11-28 16_47_44](https://user-images.githubusercontent.com/125273/69822697-edf76400-11fe-11ea-83e3-eca3c2c53855.gif)

#### Expected behaviour
Gifski installs (hangs in toggled state)
Gifski enables (stays in toggled state)

**Comment by sindresorhus** [comment]
Try Kap v3.0.1. It fixed a bug with installing plugins.

https://github.com/wulkano/kap/releases/tag/v3.0.1
