### ISSUE TITLE
exports always fail

### ISSUE THREAD

**Issue by VinSpee** [sindresorhus/kap-gifski#3]
Hi! I freshly installed Kap (v3.0.1) and when I try to save a GIF, the export (with gifski) fails every time. I can successfully export to a plain gif and also can successfully export to other services (streamable, now). Any ideas or what I can do to help diagnose?

![image](https://user-images.githubusercontent.com/582828/71742556-31617580-2e30-11ea-8d17-ba827b190649.png)

**Comment by VinSpee** [comment]
I've tried disabling/re-enabling

**Comment by VinSpee** [comment]
(I do have Gifski installed and can successfully process files with it)

**Comment by sindresorhus** [comment]
I just tried same Kap version and cannot reproduce.

@karaggeorge We really need to show a more informative error message when something happens.

**Comment by karaggeorge** [comment]
I think the next big thing is coming up with a new plugin API. In that we can look into allowing plugins to fail with a reason that we can display. And then we can still catch unhandled errors showing that generic message

**Comment by sindresorhus** [comment]
If a plugin throws for whatever reason, I think we should show the full error somehow. We should not hide away the real problem. In the export window, either as a alert sheet or a tooltip on the "Export Failed" text.

**Comment by sindresorhus** [comment]
@VinSpee Can you try again with the latest Kap version? https://github.com/wulkano/kap/releases/tag/v3.2.1 It should be better at reporting errors.

**Comment by VinSpee** [comment]
yikes! I can't even launch post-upgrade:


![image](https://user-images.githubusercontent.com/582828/81576462-48801900-9376-11ea-9a8e-ba1cfa1612ba.png)

**Comment by VinSpee** [comment]
> yikes! I can't even launch post-upgrade:

clearing `Application Support/kap` cleared it up, and `export with gifski` is working now too. Thanks

**Comment by karaggeorge** [comment]
That is an issue with kap-streamable. I've opened a PR a while ago, but it's still open: https://github.com/kevva/kap-streamable/pull/4
